### ISSUE TITLE
Problem with custom macro attributes in the `.gitattributes` file

### ISSUE THREAD

**Issue by SicroAtGit** [fantaisie-software/purebasic-repository-template#4]
I use the `.gitattributes` file provided here in repository (A) and repository (B). Since repository (B) contains code that depends on the code in repository (A), I have `git subtree`ed repository (A) into a subdirectory in repository (B).

The problem is that repository (B) now has a `.gitattributes` file in a subdirectory that contains custom macro attributes, [which Git does not allow](https://git-scm.com/docs/gitattributes#_defining_macro_attributes).

The solution was for me to modify the `.gitattributes` file in repository (A) before applying `git subtree` so that it no longer uses custom macro attributes.

I suggest removing the custom macro attributes from the `.gitattributes` file. If there are no objections, I would create the PR for this change.

**Comment by tajmone** [comment]
Done!

Also, remember that for special use cases we can always create an alternate version of the template via branches — GitHub (AFAIR) allows chosing a specific branch when applying a template to a new repository. So we could also have dedicated branches with alternative configurations to match different use cases. So far I simply didn't stumble across a recurrent need of such specialized template that would justify maintaining a branch, but I'll happily host such branches if third parties feel the need for them.

**Comment by SicroAtGit** [comment]
Thanks!

> GitHub (AFAIR) allows chosing a specific branch when applying a template to a new repository. So we could also have dedicated branches with alternative configurations to match different use cases.

That would be good, but if you create a repository from a template repository at GitHub, you have the same options as when you fork a repository: Only the default branch is taken or, if the checkbox "Include all branches" is activated, all branches are taken over. So, a single branch other than the default branch is not available for selection.

[GitHub Doc: Creating a repository from a template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template)

Sure, it is still possible to take over all branches and later delete all branches except the branch you want to have, which you then rename to the default branch.

**Comment by tajmone** [comment]
I thought there was an option to include a specific branch, I must have either remembered wrong or I'm confused with another Git service that does — it's a pity though, it would have been a useful feature to have.
